### ISSUE TITLE
Licentieserver

### ISSUE THREAD

**Issue by niekbosch** [sara-nl/clouddocs#33]
A tip about using a license server could be added to the documentation:

> Especially for license servers with fixed mac:
> 
> 1) click on your internal network
> 2) click on “reserve”, top-right
> 3) select the number of addresses, in my case 1 for one server
> 4) click on “add to new virtual network”, give it a nice name (in my case: delft3d-license)
> 5) open “advanced”
> 6) select your address range
> 7) as first mac address, I choose something at the end of the range, so something ending in .253
> 8) hit “reserve”
> 
> Now create a license server, and as network, choose your reservation. Your machine will now have a fixed mac and address, suitable for license servers using FlexLM and so on.

**Comment by markus-sara** [comment]
Yes! It could be added to the documentation! If you create a pull request, we will consider it :-)
